### ISSUE TITLE
Not working for Mac?

### ISSUE THREAD

**Issue by vonmon2** [tim241/cuphead_wine_instructions#1]
So basically, I'm able to clone wine and download the patch.  However, the terminal doesn't know what file to patch when I try to run the next step, and so I'm stuck there.
I just get this output:

```
can't find file to patch at input line 11

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:

|commit 4c74f750106adcee0f1706b366ecfc6ee7029b72

|Author: Tim Wanders <timwanders241@gmail.com>

|Date:   Tue Oct 3 21:51:33 2017 +0200

|

|    Fixed crash for CupHead

|

|diff --git a/dlls/setupapi/stubs.c b/dlls/setupapi/stubs.c


|index 990974d9b9..aa680d4b44 100644

|--- a/dlls/setupapi/stubs.c

|+++ b/dlls/setupapi/stubs.c

--------------------------
```

(Sorry, I have no idea how to format)

If I navigate all the way through the Steam directory and select the cuphead executable to patch, I get a massive block of ?'s and random symbols/letters.

**Comment by tim241** [comment]
when you cloned the wine source..you should be able to cd into it..and then wget and apply that patch, Are you in the right directory?

**Comment by vonmon2** [comment]
The wine directory right? For Mac, my wine directory is called .wine

**Comment by vonmon2** [comment]
It just says 

-bash: cuphead.patch: No such file or directory

**Comment by tim241** [comment]
no.. after you did got clone, cd into that newly made directory which contains the wine source

**Comment by vonmon2** [comment]
Let me try cloning again and retrying it that way!

**Comment by tim241** [comment]
okay :)

**Comment by vonmon2** [comment]
Thanks so much for trying to help, if it doesn't work that's okay! I'll just have to wait for an official Mac release :)

**Comment by tim241** [comment]
@vonmon2 it's okay, we can try at least :+1:

**Comment by vonmon2** [comment]
It's working!! (I think...)

**Comment by vonmon2** [comment]
I'm waiting on Wine to compile now! If the last step works, this might just be it!

**Comment by tim241** [comment]
Okay, if the make command completed successfully you need to execute ```make install prefix=/usr/local``` and not the ```make install``` command from the README

**Comment by vonmon2** [comment]
should I include the 'sudo' before 'make'?

**Comment by tim241** [comment]
Only with the ```make install prefix=/usr/local``` command :)

**Comment by vonmon2** [comment]
man this thing has a lot of making to do

**Comment by tim241** [comment]
yes, it can take up to about 1 hour to build , so relax and drink some coffee while waiting! :+1:

**Comment by vonmon2** [comment]
okay, what should it look like when I do the last command?

**Comment by vonmon2** [comment]
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
version=`(GIT_DIR=../../.git git describe HEAD 2>/dev/null || echo "wine-2.18") | sed -n -e '$s/\(.*\)/const char wine_build[] = "\1";/p'` && (echo $version | cmp -s - version.c) || echo $version >version.c || (rm -f version.c && exit 1)
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: `libdinput.a' is up to date.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all'.
STRIPPROG="strip" ./tools/install-sh  dlls/acledit/acledit.dll.so /usr/lib/wine/acledit.dll.so
mkdir: /usr/lib/wine: Operation not permitted
mkdir: /usr/lib/wine: Operation not permitted
make: *** [dlls/acledit/install-lib] Error 1


Just got this

**Comment by vonmon2** [comment]
and now we wait...

**Comment by vonmon2** [comment]
alright... I think it's finished.  Do I just try and start up the game now or...?

**Comment by vonmon2** [comment]
just to be safe and make sure I don't screw anything up, my steam is in that OTHER wine directory, is that a problem?

**Comment by tim241** [comment]
execute ```wine --version``` and give me the output

**Comment by vonmon2** [comment]
wine-2.18-45-gb34ea10112

**Comment by tim241** [comment]
and now give me the output of ```/usr/local/bin/wine --version```

**Comment by vonmon2** [comment]
wine-2.18-45-gb34ea10112

Same thing

**Comment by tim241** [comment]
good, now launch the game

**Comment by vonmon2** [comment]
Yikes, just got this.

wine: '/Users/owner/.wine' is a 64-bit installation, it cannot be used with a 32-bit wineserver.

**Comment by vonmon2** [comment]
I tried to load up steam using 

wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Steam/Steam.exe

since that's where I have my Windows Steam.exe, but I think now I have two different versions of wine on my Mac

**Comment by tim241** [comment]
If you want to redownload the game and Steam to get it working, ```rm -rf /Users/owner/.wine```

**Comment by tim241** [comment]
I don't think you have 2 wine versions in your system, if I'm correct we just removed the old installation and replaced that one with the new patched version

**Comment by vonmon2** [comment]
ohhh okay, sorry I think I totally just disoriented myself in my computer, how should I get back to steam?

**Comment by tim241** [comment]
You mean the Windows steam?

**Comment by vonmon2** [comment]
Yeah, yeah

**Comment by vonmon2** [comment]
if I were to re download it, do I then just try and open it with wine?

**Comment by tim241** [comment]
You need a 64 bit version of wine for that..I didn't try that yet, but if you want to compile wine again, I can search it :)

**Comment by tim241** [comment]
yes, if you redownload steam + the game you can open it with wine

**Comment by vonmon2** [comment]
okay, so as of now I redownloaded the windows steam setup exe and I'm now trying to open it using wine from my download directory.  I'm getting some CreateInstance errors and the app is running, but I can't really see anything

**Comment by vonmon2** [comment]
I read online somewhere I might have to download some fonts somewhere for it to work?

**Comment by tim241** [comment]
wine should take care of everything :)

**Comment by tim241** [comment]
don't worry, getting warnings/errors is normal in wine :)

**Comment by vonmon2** [comment]
Sorry, I'm totally lost.  After I download the Steamsetup.exe for windows, what command could I use to actually open and set up steam in the new wine patch? I can't seem to reach the one I had before anymore. Do I perhaps have to delete the other windows steam I have first?

**Comment by tim241** [comment]
so after you installed Steam with wine, you can go into your .wine/drive_c/Program Files/Steam directory

**Comment by tim241** [comment]
you can find and execute Steam.exe there

**Comment by vonmon2** [comment]
winedevice.exe(5406,0x407fa000) malloc: *** error for object 0x111111: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug


Ugh, im really sorry, this is so close

**Comment by tim241** [comment]
can you try to remove your .wine folder completely, then execute and install steam through its installer and then launch it?

**Comment by vonmon2** [comment]
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

Is what I get before a bunch of errors

**Comment by tim241** [comment]
okay, install those fonts :)

**Comment by vonmon2** [comment]
My .wine/drive_c/Program Files/Steam directory doesn't exist anymore unfortunately:(

**Comment by tim241** [comment]
that's fine for now, now

**Comment by tim241** [comment]
download the steam installer for Windows and install that

**Comment by vonmon2** [comment]
aight, I had to do the 'make' command again, so I might be a few.  I'll try all that right after!

**Comment by vonmon2** [comment]
This game had better be amazing 😆

**Comment by tim241** [comment]
why did you have to do ```make```again? :o

**Comment by vonmon2** [comment]
I didn't know which version of the fonts to download, so I looked it up and someone said to config with some special parameters

**Comment by tim241** [comment]
okay :)

**Comment by vonmon2** [comment]
As you can see, I'm very much a novice at this :)

**Comment by tim241** [comment]
it's okay :)

**Comment by vonmon2** [comment]
okay, it FINALLY finished making.

**Comment by vonmon2** [comment]
How exactly should I go about installing free type 😭

**Comment by vonmon2** [comment]
wait I think I got it

**Comment by vonmon2** [comment]
IT WORKED

**Comment by vonmon2** [comment]
I have to navigate steam with NO words or fonts or anything, just by memory, but IT WORKS

**Comment by vonmon2** [comment]
thank you SO MUCH for everything, you've been the most helpful person in like the last year.  Thank you again, I guess I'll go enjoy some Cuphead!!!

**Comment by tim241** [comment]
No problem and enjoy the game :+1: , good job figuring things out on your own :)
